import { chromium } from "playwright-core";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
await p.goto("http://localhost:3372/", { waitUntil: "networkidle" });
await p.waitForTimeout(2600);
const box1 = await p.locator("#work .lede").boundingBox();
await p.screenshot({ path: "/tmp/lede-index.png", clip: { x: box1.x - 20, y: box1.y - 60, width: 900, height: box1.height + 100 } });
await p.locator("#stack").scrollIntoViewIfNeeded();
await p.waitForTimeout(500);
const box2 = await p.locator("#stack .lede").boundingBox();
await p.screenshot({ path: "/tmp/lede-stack.png", clip: { x: box2.x - 20, y: box2.y - 60, width: 900, height: box2.height + 100 } });
await b.close();
